AWSTemplateFormatVersion: 2010-09-09
Description: yaml to create the DMS infra
# Metadata: 

# Parameters: 

# Mappings: 

# Conditions: 

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: s3-bucket-phtf-db
      Tags: 
        - Key: "env"
          Value: "developer"

  rdsDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    DependsOn: S3Bucket
    Properties:
      Description: "Activates bin logs"
      Family: postgres13
      Parameters:
        "rds.logical_replication": 1
        "wal_sender_timeout": 0

  IAMManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    DependsOn: S3Bucket
    Properties:
      ManagedPolicyName: "role-dms"
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          - s3:GetObjectAcl
          - s3:GetObject
          - s3:ListBucket
          - s3:GetBucketAcl
          Resource:
          - !Join
            - ""
            - - "arn:aws:s3:::"
              - !Ref S3Bucket
            
          - !Join
            - ""
            - - "arn:aws:s3:::"
              - !Ref S3Bucket
              - /*

  IAMRole:
      Type: "AWS::IAM::Role"
      DependsOn: IAMManagedPolicy
      Properties:
          Path: "/"
          RoleName: "DMS-Role"
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                Service: dms.amazonaws.com
              Action: sts:AssumeRole
          MaxSessionDuration: 3600
          ManagedPolicyArns: 
            - !Ref IAMManagedPolicy
          Description: "Allows Database Migration Service to call AWS services on your behalf."

  RDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    DependsOn:
    - IAMManagedPolicy
    - rdsDBParameterGroup
    Properties:
      DBInstanceIdentifier: "db-shop"
      AllocatedStorage: 20
      DBInstanceClass: "db.t3.micro"
      Engine: "postgres"
      MasterUsername: "postgres"
      MasterUserPassword: "password"
      DBName: "orders"
      PreferredBackupWindow: "04:22-04:52"
      BackupRetentionPeriod: 0
      AvailabilityZone: !Sub "${AWS::Region}c"
      PreferredMaintenanceWindow: "thu:07:20-thu:07:50"
      MultiAZ: false
      EngineVersion: "13.3"
      AutoMinorVersionUpgrade: true
      LicenseModel: "postgresql-license"
      PubliclyAccessible: true
      StorageType: "gp2"
      Port: 5432
      StorageEncrypted: false
      CopyTagsToSnapshot: false
      MonitoringInterval: 60
      EnableIAMDatabaseAuthentication: false
      EnablePerformanceInsights: false
      DeletionProtection: false
      DBSubnetGroupName: "default-vpc-44ed6f39"
      VPCSecurityGroups: 
        - "sg-20eb4223"
      DBParameterGroupName: !Ref rdsDBParameterGroup
      OptionGroupName: "default:postgres-13"
      MonitoringRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/rds-monitoring-role"
      CACertificateIdentifier: "rds-ca-2019"

  DMSEndpointSource:
    Type: "AWS::DMS::Endpoint"
    DependsOn: RDSDBInstance
    Properties:
      EndpointIdentifier: "db-shop"
      EndpointType: "source"
      EngineName: "postgres"
      Username: "postgres"
      Password: "password"
      Port: 5432
      DatabaseName: "orders"
      SslMode: "none"
      ServerName: !GetAtt RDSDBInstance.Endpoint.Address 
      ExtraConnectionAttributes: "captureDDLs=Y"

  DMSEndpointTarget:
    Type: "AWS::DMS::Endpoint"
    DependsOn: RDSDBInstance
    Properties:
      EndpointIdentifier: "s3-target-1"
      EndpointType: "target"
      EngineName: "s3"
      ExtraConnectionAttributes: "bucketFolder=orders;bucketName=s3-bucket-phtf-db;cdcMaxBatchInterval=120;compressionType=NONE;csvDelimiter=,;csvRowDelimiter=\\n;DataFormat=parquet;datePartitionEnabled=false;FileSize=131072;includeOpForFullLoad=true;timestampColumnName=extracted_at;"
      SslMode: "none"
      S3Settings: 
        BucketFolder: "orders"
        BucketName: !Ref S3Bucket
        CompressionType: "NONE"
        CsvDelimiter: ","
        CsvRowDelimiter: "\\n"
        ServiceAccessRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/DMS-Role"

  DMSReplicationInstance:
    Type: "AWS::DMS::ReplicationInstance"
    DependsOn:
    - DMSEndpointSource
    - DMSEndpointTarget
    Properties:
      ReplicationInstanceIdentifier: "duplicate-data-1"
      ReplicationInstanceClass: "dms.t2.micro"
      AllocatedStorage: 50
      VpcSecurityGroupIds: 
        - "sg-20eb4223"
      AvailabilityZone: !Sub "${AWS::Region}f"
      ReplicationSubnetGroupIdentifier: "default-vpc-44ed6f39"
      PreferredMaintenanceWindow: "thu:06:25-thu:06:55"
      MultiAZ: false
      EngineVersion: "3.4.5"
      AutoMinorVersionUpgrade: true
      PubliclyAccessible: false

  DMSReplicationTask:
    Type: "AWS::DMS::ReplicationTask"
    DependsOn: DMSReplicationInstance
    Properties:
      ReplicationTaskIdentifier: "duplicate-data-prd-s3"
      SourceEndpointArn: !Ref DMSEndpointSource
      TargetEndpointArn: !Ref DMSEndpointTarget
      ReplicationInstanceArn: !Ref DMSReplicationInstance
      MigrationType: "full-load-and-cdc"
      TableMappings: "{\"rules\":[{\"rule-type\":\"selection\",\"rule-id\":\"547908318\",\"rule-name\":\"547908318\",\"object-locator\":{\"schema-name\":\"%\",\"table-name\":\"%\"},\"rule-action\":\"include\",\"filters\":[]}]}"
      ReplicationTaskSettings: "{\"Logging\":{\"EnableLogging\":false,\"LogComponents\":[{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"TRANSFORMATION\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"SOURCE_UNLOAD\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"IO\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"TARGET_LOAD\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"PERFORMANCE\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"SOURCE_CAPTURE\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"SORTER\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"REST_SERVER\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"VALIDATOR_EXT\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"TARGET_APPLY\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"TASK_MANAGER\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"TABLES_MANAGER\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"METADATA_MANAGER\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"FILE_FACTORY\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"COMMON\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"ADDONS\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"DATA_STRUCTURE\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"COMMUNICATION\"},{\"Severity\":\"LOGGER_SEVERITY_DEFAULT\",\"Id\":\"FILE_TRANSFER\"}],\"CloudWatchLogGroup\":null,\"CloudWatchLogStream\":null},\"StreamBufferSettings\":{\"StreamBufferCount\":3,\"CtrlStreamBufferSizeInMB\":5,\"StreamBufferSizeInMB\":8},\"ErrorBehavior\":{\"FailOnNoTablesCaptured\":true,\"ApplyErrorUpdatePolicy\":\"LOG_ERROR\",\"FailOnTransactionConsistencyBreached\":false,\"RecoverableErrorThrottlingMax\":1800,\"DataErrorEscalationPolicy\":\"SUSPEND_TABLE\",\"ApplyErrorEscalationCount\":0,\"RecoverableErrorStopRetryAfterThrottlingMax\":true,\"RecoverableErrorThrottling\":true,\"ApplyErrorFailOnTruncationDdl\":false,\"DataTruncationErrorPolicy\":\"LOG_ERROR\",\"ApplyErrorInsertPolicy\":\"LOG_ERROR\",\"ApplyErrorEscalationPolicy\":\"LOG_ERROR\",\"RecoverableErrorCount\":-1,\"DataErrorEscalationCount\":0,\"TableErrorEscalationPolicy\":\"STOP_TASK\",\"RecoverableErrorInterval\":5,\"ApplyErrorDeletePolicy\":\"IGNORE_RECORD\",\"TableErrorEscalationCount\":0,\"FullLoadIgnoreConflicts\":true,\"DataErrorPolicy\":\"LOG_ERROR\",\"TableErrorPolicy\":\"SUSPEND_TABLE\"},\"FullLoadSettings\":{\"CommitRate\":10000,\"StopTaskCachedChangesApplied\":false,\"StopTaskCachedChangesNotApplied\":false,\"MaxFullLoadSubTasks\":8,\"TransactionConsistencyTimeout\":600,\"CreatePkAfterFullLoad\":false,\"TargetTablePrepMode\":\"DROP_AND_CREATE\"},\"TargetMetadata\":{\"ParallelApplyBufferSize\":0,\"ParallelApplyQueuesPerThread\":0,\"ParallelApplyThreads\":0,\"TargetSchema\":\"\",\"InlineLobMaxSize\":0,\"ParallelLoadQueuesPerThread\":0,\"SupportLobs\":true,\"LobChunkSize\":0,\"TaskRecoveryTableEnabled\":false,\"ParallelLoadThreads\":0,\"LobMaxSize\":32,\"BatchApplyEnabled\":false,\"FullLobMode\":false,\"LimitedSizeLobMode\":true,\"LoadMaxFileSize\":0,\"ParallelLoadBufferSize\":0},\"BeforeImageSettings\":null,\"ControlTablesSettings\":{\"historyTimeslotInMinutes\":5,\"HistoryTimeslotInMinutes\":5,\"StatusTableEnabled\":false,\"SuspendedTablesTableEnabled\":false,\"HistoryTableEnabled\":false,\"ControlSchema\":\"\",\"FullLoadExceptionTableEnabled\":false},\"LoopbackPreventionSettings\":null,\"CharacterSetSettings\":null,\"FailTaskWhenCleanTaskResourceFailed\":false,\"ChangeProcessingTuning\":{\"StatementCacheSize\":50,\"CommitTimeout\":1,\"BatchApplyPreserveTransaction\":true,\"BatchApplyTimeoutMin\":1,\"BatchSplitSize\":0,\"BatchApplyTimeoutMax\":30,\"MinTransactionSize\":1000,\"MemoryKeepTime\":60,\"BatchApplyMemoryLimit\":500,\"MemoryLimitTotal\":1024},\"ChangeProcessingDdlHandlingPolicy\":{\"HandleSourceTableDropped\":true,\"HandleSourceTableTruncated\":true,\"HandleSourceTableAltered\":true},\"PostProcessingRules\":null}"

# Outputs: